[opener]
edit = [
	{ run = "tmux send-keys -t \"${HELIX_PANE:-$TMUX_PANE}\" \":onc \\\"${@}\\\"\" Enter; tmux kill-pane", block = false },
]
open = [
	{ run = "tmux send-keys -t \"${HELIX_PANE:-$TMUX_PANE}\" \":onc \\\"${@}\\\"\" Enter; tmux kill-pane", block = false },
]

[mgr]
show_hidden = true
