[opener]
edit = [
	{ run = "tmux send-keys -t $HELIX_PANE \":onc \\\"${@}\\\"\" Enter && tmux kill-pane -t $TMUX_PANE", block = false },
]
open = [
	{ run = "tmux send-keys -t $HELIX_PANE \":onc \\\"${@}\\\"\" Enter && tmux kill-pane -t $TMUX_PANE", block = false },
]

[mgr]
show_hidden = true
